### ISSUE TITLE
Use ele_ft

### ISSUE THREAD

**Issue by boldtrn** [nst-guide/osm-liberty-topo#12]
I just saw that you calculate elevation in feet. OMT provides the filed "ele_ft", maybe this would be easier to use?

**Comment by kylebarron** [comment]
I did notice that belatedly. Though since it's really easy to convert to feet in the style, to me it seems like a waste of space to store both, so I removed `ele_ft` in my fork: https://github.com/nst-guide/openmaptiles/commit/bce9be6b3e3635ff9b76f639c89eba419360c863

**Comment by boldtrn** [comment]
Ah ok, just wanted to mention it :).

> Though since it's really easy to convert to feet in the style, to me it seems like a waste of space to store both

While this might not be relevant for your use case, there are other map clients as well, that might not allow these calculations in the style. I think that's the reason why OMT initially added this. AFAIK, the overall mvt size shouldn't grow that much due to this, mvt is pretty good at optimizing this stuff.

**Comment by kylebarron** [comment]
Thanks for the comment!

> there are other map clients as well, that might not allow these calculations in the style

Good point, I hadn't thought of that. I've only used Mapbox GL JS with it so far.
